baseURL: https://jira.meiqia.com
username: <YOUR-JIRA-USERNAME>
password: <YOUR-JIRA-PASSWORD>
project: 基础架构, LiveChat, 呼叫, 茶馆
issueType: 任务, 改进, 故事, 子任务, 故障, Bug
finishedStatus: 完成, 关闭
canceledStatus: 取消, 拒绝
updatedSince: -7d
